{"name": "test_authorization_error", "status": "failed", "statusDetails": {"message": "AssertionError", "trace": "authorization_page = <pages.authorization_page.AuthorizationPage object at 0x000002992F40F3D0>\n\n    def test_authorization_error(authorization_page):\n        authorization_page.click_to_login_button()\n        authorization_page.set_wrong_phone_number()\n        authorization_page.click_first_checkbox()\n        authorization_page.click_get_code_btn()\n>       authorization_page.verify_wrong_number_message_rapid_auth_page()\n\ntests\\test_authorization.py:43: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <pages.authorization_page.AuthorizationPage object at 0x000002992F40F3D0>\n\n    @allure.step('verify wrong number error message - rapid authorization page ')\n    def verify_wrong_number_message_rapid_auth_page(self):\n        actual_result = self.get_text_title_of_element(AuthorizationLocators.WRONG_NUMBER_MESSAGE_RAPID_AUTH_PAGE)\n>       assert actual_result == 'Неправильный номер'\nE       AssertionError\n\npages\\authorization_page.py:911: AssertionError"}, "steps": [{"name": "clicking to \"Login\" button", "status": "passed", "start": 1692341424787, "stop": 1692341486916}, {"name": "input wrong phone number", "status": "passed", "start": 1692341486917, "stop": 1692341487928}, {"name": "click first check-box", "status": "passed", "start": 1692341487928, "stop": 1692341488239}, {"name": "click get-code btn", "status": "passed", "start": 1692341488239, "stop": 1692341488732}, {"name": "verify wrong number error message - rapid authorization page ", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"C:\\Users\\Owner\\PycharmProjects\\LifeHelp\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\Owner\\PycharmProjects\\LifeHelp\\pages\\authorization_page.py\", line 911, in verify_wrong_number_message_rapid_auth_page\n    assert actual_result == 'Неправильный номер'\n"}, "start": 1692341488732, "stop": 1692341488921}], "start": 1692341424787, "stop": 1692341488937, "uuid": "6c8b241a-065d-49e5-aff2-4f1ea13c1190", "historyId": "747a7077b32c59fe608ebe6263a7672f", "testCaseId": "192146f7a0b5ba73c91479f2aa0b8d65", "fullName": "tests.test_authorization#test_authorization_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_authorization"}, {"name": "host", "value": "DESKTOP-MNCDD93"}, {"name": "thread", "value": "29480-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_authorization"}]}