{"name": "test_registrations_error_messages[missing_number_password]", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message:", "trace": "authorization_page = <pages.authorization_page.AuthorizationPage object at 0x000001EEB4CE6380>, first = 'aigul.shafigullina@yandex.ru'\nsecond = 'lifehelp@', third = 'lifehelp@', fourth = 'Пароль должен содержать хотя бы одну цифру'\n\n    @pytest.mark.parametrize('first, second, third, fourth', (case_1, case_2, case_3, case_4, case_5, case_6),\n                                 ids=['phone_instead_email', 'not_matching_passwords', 'missing_number_password',\n                                      \"missing_symbol_password\", \"cyrillic_password\", \"missing_latin_letter_password\" ])\n    def test_registrations_error_messages(authorization_page, first, second, third, fourth):\n        authorization_page.click_to_login_button()\n        authorization_page.click_to_login_w_password_button()\n>       authorization_page.click_register_hypertext()\n\ntests\\test_authorization.py:710: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \npages\\authorization_page.py:396: in click_register_hypertext\n    self.to_click(AuthorizationLocators.REGISTER_HYPERTEXT)\nbase\\base_object.py:17: in to_click\n    self.is_clickable(locator).click()\nbase\\base_object.py:14: in is_clickable\n    return self.wait.until(ec.element_to_be_clickable(locator))\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"cfb21194f8be50633612cb22baca0b2a\")>\nmethod = <function element_to_be_clickable.<locals>._predicate at 0x000001EEB4C7AC20>, message = ''\n\n    def until(self, method, message: str = \"\"):\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value does not evaluate to ``False``.\n    \n        :param method: callable(WebDriver)\n        :param message: optional message for :exc:`TimeoutException`\n        :returns: the result of the last call to `method`\n        :raises: :exc:`selenium.common.exceptions.TimeoutException` if timeout occurs\n        \"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.monotonic() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, \"screen\", None)\n                stacktrace = getattr(exc, \"stacktrace\", None)\n            time.sleep(self._poll)\n            if time.monotonic() > end_time:\n                break\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message:\n\nvenv\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py:95: TimeoutException"}, "steps": [{"name": "clicking to \"Login\" button", "status": "passed", "start": 1692080198879, "stop": 1692080203677}, {"name": "clicking to \"Login with password\" button", "status": "passed", "start": 1692080203677, "stop": 1692080204143}, {"name": "click \"register\" hypertext", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \n\n", "trace": "  File \"C:\\Users\\Owner\\PycharmProjects\\LifeHelp\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\Owner\\PycharmProjects\\LifeHelp\\pages\\authorization_page.py\", line 396, in click_register_hypertext\n    self.to_click(AuthorizationLocators.REGISTER_HYPERTEXT)\n  File \"C:\\Users\\Owner\\PycharmProjects\\LifeHelp\\base\\base_object.py\", line 17, in to_click\n    self.is_clickable(locator).click()\n  File \"C:\\Users\\Owner\\PycharmProjects\\LifeHelp\\base\\base_object.py\", line 14, in is_clickable\n    return self.wait.until(ec.element_to_be_clickable(locator))\n  File \"C:\\Users\\Owner\\PycharmProjects\\LifeHelp\\venv\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 95, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "start": 1692080204143, "stop": 1692080209854}], "parameters": [{"name": "first", "value": "'aigul.shafigullina@yandex.ru'"}, {"name": "second", "value": "'lifehelp@'"}, {"name": "third", "value": "'lifehelp@'"}, {"name": "fourth", "value": "'Пароль должен содержать хотя бы одну цифру'"}], "start": 1692080198878, "stop": 1692080209875, "uuid": "9d11fc00-b9f1-4a68-86c6-672267f3b350", "historyId": "d777105035ae2ffcf795ba830c2515e5", "testCaseId": "01609061ad681f07a7f52b36ebc3800e", "fullName": "tests.test_authorization#test_registrations_error_messages", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_authorization"}, {"name": "host", "value": "DESKTOP-MNCDD93"}, {"name": "thread", "value": "25632-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_authorization"}]}